// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: user_profile_queries.sql

package db

import (
	"context"
)

const getUserProfileById = `-- name: GetUserProfileById :one
SELECT id, first_name, last_name, created_at, updated_at, image_url
FROM user_profile
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserProfileById(ctx context.Context, id int32) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileById, id)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}
